version: "3.8"

services:
  webapp:
    image: vsc55/loganalyzer:latest
    container_name: LogAnalyzer
    restart: always
    ports:
      - "80:80"
    environment:
      - TZ=Europe/Madrid
      - HTTP_PORT=80
    volumes:
      - ./data:/data
      - ./logs:/var/log